spring:
  #CONFIG BASICO
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop


  application:
    name: spring.application.name
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    username: postgres
    password: minha_senha

    #ESSE PODE SER OPCIONAL POREM E RECOMENDADO CRIA-LO
    driver-class-name: org.postgresql.Driver


server:
  port: 8081

