services:
  banco-de-dados:
    image: postgres
    environment:
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: learn
    ports:
      - "5432:5432"
  sistema-de-mensageria-rabbitMQ:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: alex
      RABBITMQ_DEFAULT_PASS: alex
    ports:
      - "5672:5672"
      - "15672:15672"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper