services:
  banco-de-dados:
    image: postgres
    environment:
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: learn
    ports:
      - 5432:5432
  sistema-de-mensageria:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: alex
      RABBITMQ_DEFAULT_PASS: alex
    ports:
      - 5672:5672
      - 15672:15672